---
- name: Setup Web Servers and Database
  hosts: webservers
  become: yes  # Si necesitas privilegios de sudo
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install necessary packages
      apt:
        name:
          - nginx
          - git
        state: present

- name: Setup Database
  hosts: databases
  become: yes  # Si necesitas privilegios de sudo
  vars:
    db_name: mydatabase
    db_user: prueba  # Cambia esto por el nombre de usuario de tu base de datos
    db_password: Prueba123.  # Cambia esto por la contraseña de tu base de datos

  tasks:
    - name: Ensure the database is running
      postgresql_db:
        name: "{{ db_name }}"
        state: present
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ ansible_host }}"  # Usa ansible_host para obtener el endpoint
        login_port: 5432

    - name: Ensure the database user exists
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        state: present
        login_host: "{{ ansible_host }}"
        login_port: 5432

